
version: "3"
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: emprestimo_adm
      POSTGRES_PASSWORD: password
      POSTGRES_DB: emprestimo_db
    volumes:
      - ./db-data/:/var/lib/postgresql/data/